### ISSUE TITLE
cd - doesn't work

### ISSUE THREAD

**Issue by ddnomad** [dczhu/ltcd#1]
`cd -` simply brings me to the previous directory (instead of showing global dirs list). Also it would be good to have a built-n help as well as an ability to remap Alt+<key> mappings to something else (as I use `i3wm` that has Alt-A for other purposes). 

So overall, right now I have to way to bring up global dirs list (command doesn't work, mapping got intercepted by `i3wm`).

P.S. There is also a dozen of different suggestions but I might find time to contribute a bit to make them a real thing.

**Comment by dczhu** [comment]
Thanks for using and your feedback.

To bring up global dirs list, use "cd -?" not "cd -". I intended to let the new cd be compatible with the original cd - It means "cd -" will bring you back to the previous dir.

Regarding key mapping, you could easily choose an unused keybinding and enable it at the end of ltcd.

BTW, in README, I need to mention the use of "cxpgrep" command in ltcd -- cxpgrep is an extended grep command I developed for some purposes (https://github.com/dczhu/cxpgrep). Will add the code soon.

**Comment by ddnomad** [comment]
Oh, my bad I missed `?` char in README. It would be decent to use code markup in README file as it's easier to comprehend that way. 

Except for that the issue can be closed. Thank you for the answer!
